Gallery/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Gallery.Models
{
    public class Comment
    {
        public int? Id { get; set; }
        [StringLength(200, MinimumLength = 3, ErrorMessage = "Kirjelduse pikkus peab olema 3-200 märki")]
        [Display(Name = "Comment")]
        public string AddedComment { get; set; }
        [DataType(DataType.Date)]
        public DateTime? DateAdded { get; set; }
        public int? PictureId { get; set; }

        public Picture Picture { get; set; }
        public ApplicationUser User { get; set; }

        public string UserId { get; set; }

    }
}

Gallery/Models/Picture.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Gallery.Models
{
    public class Picture
    {
        public int? Id { get; set; }

        [Required(ErrorMessage = "Pealkirja sisestamine on kohustuslik")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Pealkirja pikkus peab olema 3-50 märki")]
        public string Title { get; set; }
        [StringLength(100, MinimumLength = 3, ErrorMessage = "Kirjelduse pikkus peab olema 3-100 märki")]
        public string Description { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Date added")]
        public DateTime? DateAdded { get; set; }
        public int? FolderId { get; set; }

        public ICollection<Comment> Comments { get; set; }
        public ICollection<Vote> Votes { get; set; }

        
        public ApplicationUser User { get; set; }
        public string UserId { get; set; }
        public Folder Folder { get; set; }
        [Display(Name = "Picture")]
        public byte[] AddedPicture { get; set; }
    }
}

Gallery/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Gallery.Models;
using Microsoft.AspNet.Identity;
using Gallery.CustomFilters;

namespace Gallery.Controllers
{
    public class CommentsController : Controller
    {
        private GalleryContext db = new GalleryContext();

        // GET: Comments
        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.Picture).Include(c => c.User);
            return View(comments.ToList());
        }

        // GET: Comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: Comments/Create
        public ActionResult Create(int id)
        {
            ViewBag.PictureId = id; 
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,AddedComment,DateAdded,PictureId")] Comment comment, int pictureId)
        {
            if (ModelState.IsValid)
            {
                comment.PictureId = pictureId;
                comment.DateAdded = DateTime.Now;
                db.Comments.Add(comment);
                comment.UserId = User.Identity.GetUserId();
                db.SaveChanges();
                return RedirectToAction("Index", "Picture", new { Id = db.Pictures.Find(pictureId).FolderId });
            }

            ViewBag.PictureId = new SelectList(db.Pictures, "Id", "Title", comment.PictureId);
            return RedirectToAction("Index", "Picture", new { Id = db.Pictures.Find(pictureId).FolderId });
        }

        // GET: Comments/Edit/5
        [AuthLog(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.PictureId = new SelectList(db.Pictures, "Id", "Title", comment.PictureId);
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthLog(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "Id,AddedComment,DateAdded,PictureId")] Comment comment, int pictureId)
        {
            if (ModelState.IsValid)
            {
                
                Comment oldComment = db.Comments.Find(comment.Id);
                oldComment.PictureId = pictureId;
                oldComment.AddedComment = comment.AddedComment;

                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PictureId = new SelectList(db.Pictures, "Id", "Title", comment.PictureId);
            return View(comment);
        }

        // GET: Comments/Delete/5
        [AuthLog(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthLog(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

Gallery/Controllers/VotesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Gallery.Models;

namespace Gallery.Controllers
{
    public class VotesController : Controller
    {
        private GalleryContext db = new GalleryContext();

        // GET: Votes
        public ActionResult Index()
        {
            var votes = db.Votes.Include(v => v.Picture).Include(v => v.User);
            return View(votes.ToList());
        }

        // GET: Votes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vote vote = db.Votes.Find(id);
            if (vote == null)
            {
                return HttpNotFound();
            }
            return View(vote);
        }

        // GET: Votes/Create
        public ActionResult Create(int id)
        {
            var vote = new Vote();
            vote.PictureId = (Int32)id;   
            db.Votes.Add(vote);
            db.SaveChanges();

            return RedirectToAction("Index", "Picture", new { Id = db.Pictures.Find(id).FolderId });
        }

    // POST: Votes/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
    //[HttpPost]
    //    [ValidateAntiForgeryToken]
    //    public ActionResult Create([Bind(Include = "Id,PictureId")] Vote vote, int pictureId)
    //    {
    //        if (ModelState.IsValid)
    //        {
    //            vote.PictureId = pictureId;
    //            db.Votes.Add(vote);
    //            db.SaveChanges();
    //            return RedirectToAction("Index", "Folder");
    //        }

    //        ViewBag.PictureId = new SelectList(db.Pictures, "Id", "Title", vote.PictureId);
    //        //ViewBag.UserId = new SelectList(db.Users, "Id", "UserName", vote.UserId);
    //        return View(vote);
    //    }

        // GET: Votes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vote vote = db.Votes.Find(id);
            if (vote == null)
            {
                return HttpNotFound();
            }
            ViewBag.PictureId = new SelectList(db.Pictures, "Id", "Title", vote.PictureId);
            //ViewBag.UserId = new SelectList(db.Users, "Id", "UserName", vote.UserId);
            return View(vote);
        }

        // POST: Votes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,PictureId")] Vote vote)
        {
            if (ModelState.IsValid)
            {
                db.Entry(vote).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PictureId = new SelectList(db.Pictures, "Id", "Title", vote.PictureId);
            //ViewBag.UserId = new SelectList(db.Users, "Id", "UserName", vote.UserId);
            return View(vote);
        }

        // GET: Votes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vote vote = db.Votes.Find(id);
            if (vote == null)
            {
                return HttpNotFound();
            }
            return View(vote);
        }

        // POST: Votes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vote vote = db.Votes.Find(id);
            db.Votes.Remove(vote);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gallery/Views/Picture/Comment.cshtml
@model Gallery.Models.Comment

@{
    ViewBag.Title = "Comment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Comment</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Comment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AddedComment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddedComment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddedComment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateAdded, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateAdded, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateAdded, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PictureId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PictureId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PictureId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Comment" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Gallery/Views/Picture/Create.cshtml
@model Gallery.Models.Picture

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Picture", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Picture</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FolderId, "FolderId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FolderId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FolderId, "", new { @class = "text-danger" })
            </div>
        </div>

        <label for="file">Upload Image:</label>
        <input type="file" name="file" id="file" style="width: 100%;" />
           
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}




@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Gallery/Views/Picture/Delete.cshtml
@model Gallery.Models.Picture

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Picture</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddedPicture)
        </dt>

        <dd>
            @if (Model.AddedPicture != null)
            {
                <img src='@Url.Action("Show", "Picture", new { id = Model.Id })' />
            }
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> 
        </div>
    }
</div>

Gallery/Views/Picture/Details.cshtml
@model Gallery.Models.Picture

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Picture</h4>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateAdded)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>
            
        <dd>
            @ViewBag.UserName
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AddedPicture)
        </dt>

        <dd>
           @if (Model.AddedPicture != null)
           {
            <img style="width:100%;" src='@Url.Action("Show", "Picture", new { id = Model.Id })' />
           }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>
        <dd>
            @if (Model.Comments != null)
            {
                foreach (Gallery.Models.Comment item in ViewBag.Comments)
                {
                    if (item.UserId == null)
                    {
                        <p>Anonymous:</p><p style="font-style:italic;">@item.AddedComment</p>
                    }
                    else if (item.UserId != null)
                    {
                        <p>@item.User.NickName:</p><p style="font-style:italic;">@item.AddedComment</p>
                    }
                }
            }

            
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
</p>

Gallery/Views/Picture/Edit.cshtml
@model Gallery.Models.Picture


@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
@if (Model.AddedPicture != null)
 {
     <img src='@Url.Action("Show", "Picture", new { id = Model.Id })' />
 }

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Picture</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FolderId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FolderId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.FolderId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default"/>
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Gallery/Views/Picture/Index.cshtml
@model IEnumerable<Gallery.Models.Picture>






@{
    
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>@ViewBag.FolderTitle</h2>
@ViewBag.UserName

<p>
    @Html.ActionLink("Create New", "Create", new { id = ((List<Gallery.Models.Picture>) Model)[0].FolderId })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>        
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AddedPicture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateAdded)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Votes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comments)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
        
            @if (item.AddedPicture != null)
            {
                <div class="col-md-10">
                    <a href="#" class="thumbnail" data-toggle="modal" data-target="#lightbox">
                        <img src='@Url.Action("Show", "Picture", new { id = item.Id })' style="width:90%;" />
                    </a>
               </div>
            <div id="lightbox" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <div class="modal-content">
                        <div class="modal-body">
                            <img src="" alt="" />
                        </div>
                    </div>
                </div>
            </div>
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateAdded)
        </td>
        <td>
            @item.Votes.Count
        </td>
        <td>
            @item.Comments.Count
        </td>
        <td>
            @item.User.NickName
        </td>
        <td>
            
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id }) |
            @Html.ActionLink("Add comment", "Create", "Comments", new { id = item.Id }, null) |
            @Html.ActionLink("Vote", "Create", "Votes", new { id = item.Id }, null)
 
        </td>
    </tr>
}

</table>